server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIdAddress: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customers(?<segment>/?.*),$\{segment}
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products(?<segment>/?.*),$\{segment}
        - id: order-management-service
          uri: lb://order-management-service
          predicates:
            - Path=/order-managements/**
          filters:
            - RewritePath=/order-management(?<segment>/?.*),$\{segment}
