server:
  port: 4005

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIdAddress: true

spring:
   application:
      name: customer-service