server:
  port: 5000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIdAddress: true

spring:
   application:
      name: wallet-api-gateway
   cloud:
      gateway:
      discovery:
         locator:
            enabled: true
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway