server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIdAddress: true

spring:
  application:
    name: wallet-api-gateway
  cloud:
    gateway:
      routes:
        - id: wallet-customer-service
          uri: http://localhost:4002/
          predicates:
            - Path=/customers/**
        - id: second-microservice
          uri: http://localhost:8082/
          predicates:
            - Path=/second/**
management:
   endpoint:
      gateway:
         enabled: true
   endpoints:
      web:
         exposure:
            include: gateway
